name: piecyk
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  forui: ^0.12.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  # Pajor
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  geolocator: ^14.0.1
  logger: ^2.0.2
  intl: ^0.20.2
  fl_chart: ^1.0.0
  firebase_auth: ^5.5.4
  geocoding: ^4.0.0
  geocode: ^1.0.3
  google_sign_in_web: ^0.12.4+4
  google_sign_in: ^6.3.0
  to_csv: ^5.0.0
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
